import { ChevronDown, MoreHorizontal, Plus, UserPlus, X } from 'lucide-react'
import { useState } from 'react'

const products = ['Cyber Check 24/7', 'Cyber X-Ray', 'Cyber Phisher']
const roles = ['Admin', 'Manager', 'Member']
const buttonClass = 'inline-flex items-center justify-center rounded-md px-3 py-1.5 text-[10px] font-bold transition focus:outline-none focus:ring-2 focus:ring-brand/30'

type Member = { id: number; name: string; email: string; products: string[]; status: 'Active' | 'Inactive'; dateAdded: string }
type MemberForm = { firstName: string; lastName: string; email: string; password: string; confirmPassword: string; assignments: Record<string, string> }
type InviteRow = { email: string; role: string }
const initialMembers: Member[] = Array.from({ length: 8 }, (_, index) => ({ id: index + 1, name: 'Edwards Ralph', email: 'someuser@fakemail.com', products: ['Products'], status: 'Active', dateAdded: '8/7/2021' }))
const emptyForm: MemberForm = { firstName: '', lastName: '', email: '', password: '', confirmPassword: '', assignments: {} }
const defaultInviteRows: InviteRow[] = [{ email: 'admin@example.com', role: 'Admin' }, { email: '', role: '' }, { email: '', role: '' }]

type Modal = 'chooser' | 'add' | 'invite' | 'assignments' | 'organizations' | null

export default function OrganizationMembersPage() {
  // Stores organization members displayed in the table.
  const [members, setMembers] = useState(initialMembers)
  // Controls which member modal flow is open.
  const [modal, setModal] = useState<Modal>(null)
  // Stores the currently edited member form values.
  const [form, setForm] = useState<MemberForm>(emptyForm)
  // Tracks which member row action menu is open.
  const [openMenu, setOpenMenu] = useState<number | null>(null)
  // Shows the invite success message after saving an invitation.
  const [inviteSent, setInviteSent] = useState(false)
  // Stores the email and role rows in the multi-invite flow.
  const [inviteRows, setInviteRows] = useState(defaultInviteRows)
  // Displays the result of sending invitations.
  const [inviteError, setInviteError] = useState(false)
  // Tracks organizations selected for the member assignment flow.
  const [selectedOrganizations, setSelectedOrganizations] = useState<number[]>([])

  const updateForm = <K extends keyof MemberForm>(key: K, value: MemberForm[K]) => setForm(current => ({ ...current, [key]: value }))
  const updateAssignment = (product: string, role: string) => updateForm('assignments', { ...form.assignments, [product]: role })
  const openChooser = () => { setForm(emptyForm); setInviteSent(false); setInviteError(false); setInviteRows(defaultInviteRows); setModal('chooser') }
  const saveMember = (invite: boolean) => {
    const name = `${form.firstName} ${form.lastName}`.trim() || 'New Member'
    setMembers(current => [...current, { id: Date.now(), name, email: form.email || 'member@example.com', products: ['Products'], status: 'Active', dateAdded: '8/7/2021' }])
    if (invite) setInviteSent(true)
    else setModal(null)
  }
  const openAssignments = () => { setOpenMenu(null); setModal('assignments') }
  const toggleOrganization = (id: number) => setSelectedOrganizations(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  const updateInviteRow = (index: number, key: keyof InviteRow, value: string) => setInviteRows(current => current.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row))
  const addInviteRow = () => setInviteRows(current => [...current, { email: '', role: '' }])
  const sendInvitations = () => {
    const hasInvalidEmail = inviteRows.some(row => row.email.trim() && !row.email.includes('@'))
    setInviteError(hasInvalidEmail)
    setInviteSent(!hasInvalidEmail)
  }

  return <section className="mt-5"><div className="flex justify-end"><button onClick={openChooser} className={`${buttonClass} bg-brand text-white`}><Plus size={13} className="mr-1" />Add Members</button></div><div className="mt-5 grid grid-cols-[34px_1.2fr_1.7fr_1fr_1fr_1fr_.25fr] px-3 pb-2 text-[10px] font-semibold text-[#8586a3]"><span>□</span><span>Name</span><span>Email</span><span>Products</span><span>Status</span><span>Date added</span><span></span></div><div className="space-y-2">{members.map(member => <div key={member.id} className="relative grid grid-cols-[34px_1.2fr_1.7fr_1fr_1fr_1fr_.25fr] items-center rounded-xl bg-white px-3 py-3 text-[10px] text-navy/75 shadow-[0_4px_14px_rgba(15,41,64,0.05)]"><span>□</span><span className="font-bold text-navy">{member.name}</span><span>{member.email}</span><span>{member.products.join(', ')}</span><span className="w-fit rounded-full bg-[#c5f8dd] px-3 py-1 font-semibold text-[#12a35d]">{member.status}</span><span>{member.dateAdded}</span><button title="Member actions" onClick={() => setOpenMenu(current => current === member.id ? null : member.id)} className="text-[#8586a3]"><MoreHorizontal size={17} /></button>{openMenu === member.id && <div className="absolute right-3 top-9 z-10 w-32 rounded-md border border-[#e6e7f0] bg-white p-1 text-[10px] shadow-[0_10px_24px_rgba(15,41,64,0.14)]"><button onClick={openAssignments} className="block w-full rounded px-2 py-2 text-left hover:bg-[#f5f6ff]">View Assignments</button><button onClick={() => setOpenMenu(null)} className="block w-full rounded px-2 py-2 text-left hover:bg-[#f5f6ff]">Change</button><button onClick={() => setOpenMenu(null)} className="block w-full rounded px-2 py-2 text-left text-[#d04e4e] hover:bg-[#fff2f2]">Deactivate</button></div>}</div>)}</div><div className="mt-5 flex justify-end"><button className={`${buttonClass} bg-brand text-white`}>Save</button></div>{modal && <MemberModal type={modal} form={form} inviteSent={inviteSent} inviteRows={inviteRows} inviteError={inviteError} selectedOrganizations={selectedOrganizations} onChange={updateForm} onAssignment={updateAssignment} onInviteRowChange={updateInviteRow} onAddInviteRow={addInviteRow} onSendInvitations={sendInvitations} onToggleOrganization={toggleOrganization} onClose={() => setModal(null)} onOpenAdd={() => setModal('add')} onOpenInvite={() => setModal('invite')} onOpenOrganizations={() => setModal('organizations')} onSave={() => saveMember(false)} onInvite={() => saveMember(true)} />}</section>
}

function MemberModal({ type, form, inviteSent, inviteRows, inviteError, selectedOrganizations, onChange, onAssignment, onInviteRowChange, onAddInviteRow, onSendInvitations, onToggleOrganization, onClose, onOpenAdd, onOpenInvite, onOpenOrganizations, onSave, onInvite }: { type: Exclude<Modal, null>; form: MemberForm; inviteSent: boolean; inviteRows: InviteRow[]; inviteError: boolean; selectedOrganizations: number[]; onChange: <K extends keyof MemberForm>(key: K, value: MemberForm[K]) => void; onAssignment: (product: string, role: string) => void; onInviteRowChange: (index: number, key: keyof InviteRow, value: string) => void; onAddInviteRow: () => void; onSendInvitations: () => void; onToggleOrganization: (id: number) => void; onClose: () => void; onOpenAdd: () => void; onOpenInvite: () => void; onOpenOrganizations: () => void; onSave: () => void; onInvite: () => void }) {
  if (type === 'assignments') return <AssignmentsModal onClose={onClose} onOpenOrganizations={onOpenOrganizations} form={form} onAssignment={onAssignment} />
  if (type === 'organizations') return <OrganizationAssignmentModal selectedOrganizations={selectedOrganizations} onToggle={onToggleOrganization} onClose={onClose} />
  if (type === 'chooser') return <BaseModal title="Add New Members" onClose={onClose}><p className="mt-3 text-xs text-navy/75">You can send email invites to members, or add them directly using the options below.</p><div className="mt-auto flex gap-3"><button onClick={onOpenAdd} className={`${buttonClass} bg-brand text-white`}>Add Existing Members</button><button onClick={onOpenInvite} className={`${buttonClass} border border-brand bg-white text-brand`}>Invite New Members</button></div></BaseModal>
  if (type === 'invite') return <InviteMembersModal rows={inviteRows} sent={inviteSent} error={inviteError} onRowChange={onInviteRowChange} onAddRow={onAddInviteRow} onSend={onSendInvitations} onClose={onClose} />
  return <BaseModal title="Add Organization Member" onClose={onClose}><div className="grid grid-cols-2 gap-3"><Field label="First Name" value={form.firstName} onChange={value => onChange('firstName', value)} /><Field label="Last Name" value={form.lastName} onChange={value => onChange('lastName', value)} /></div><Field label="Email Address" value={form.email} onChange={value => onChange('email', value)} /><Field label="Password" value={form.password} onChange={value => onChange('password', value)} type="password" /><Field label="Confirm password" value={form.confirmPassword} onChange={value => onChange('confirmPassword', value)} type="password" /><p className="mt-5 text-[10px] font-bold text-navy">Products Assignments</p><p className="mt-1 text-[9px] text-navy/70">Select the products that you'd like this member to have access to.<br />Once you select a product, select a role.</p><div className="mt-3 space-y-2"><div className="grid grid-cols-[1fr_110px] text-[9px] font-bold text-[#8586a3]"><span>Product</span><span>Role</span></div>{products.map(product => <div key={product} className="grid grid-cols-[1fr_110px] items-center gap-2 text-[9px]"><label className="flex items-center gap-1"><input type="checkbox" defaultChecked className="accent-brand" />{product}</label><div className="relative"><select value={form.assignments[product] || ''} onChange={event => onAssignment(product, event.target.value)} className="h-8 w-full appearance-none rounded border border-[#e5e6ef] bg-white px-2 pr-6 text-[9px] outline-none"><option value="">Role</option>{roles.map(role => <option key={role}>{role}</option>)}</select><ChevronDown size={12} className="pointer-events-none absolute right-2 top-2 text-[#9899bc]" /></div></div>)}</div>{inviteSent && <p className="mt-4 text-[10px] font-semibold text-[#12a35d]">Success! We have invited your member via email!</p>}<div className="mt-auto flex gap-3 pt-5"><button onClick={onInvite} className={`${buttonClass} bg-brand text-white`}>Save & Add More</button><button onClick={onSave} className={`${buttonClass} border border-brand bg-white text-brand`}>Save & Close</button><button onClick={onClose} className="px-2 text-[10px] font-semibold text-[#8586a3]">Cancel</button></div></BaseModal>
}

function AssignmentsModal({ form, onAssignment, onOpenOrganizations, onClose }: { form: MemberForm; onAssignment: (product: string, role: string) => void; onOpenOrganizations: () => void; onClose: () => void }) {
  return <BaseModal title="Assignments" onClose={onClose}><p className="mt-2 text-[10px] text-navy/70">You can view and manage the assignments here.</p><div className="mt-4 rounded-lg bg-[#fafaff] p-2 text-[9px]"><div className="grid grid-cols-[1fr_1fr] px-2 pb-2 font-bold text-[#8586a3]"><span>Organization</span><span>Industry</span></div><div className="grid grid-cols-[1fr_1fr] items-center rounded bg-white px-2 py-2 text-navy shadow-sm"><span>Some Organization</span><span>Industry area name</span></div><p className="mt-4 font-bold text-navy">Products &amp; Roles</p>{products.map(product => <div key={product} className="mt-2 grid grid-cols-[1fr_100px] items-center gap-2"><label className="flex items-center gap-1"><input type="checkbox" defaultChecked className="accent-brand" />{product}</label><select value={form.assignments[product] || ''} onChange={event => onAssignment(product, event.target.value)} className="h-7 rounded border border-[#e5e6ef] bg-white px-1 text-[9px]"><option value="">Role</option>{roles.map(role => <option key={role}>{role}</option>)}</select></div>)}<button onClick={onOpenOrganizations} className={`${buttonClass} mt-4 h-8 border border-brand bg-white text-brand`}><Plus size={12} className="mr-1" />Add More</button></div><button onClick={onClose} className={`${buttonClass} mt-auto bg-brand text-white`}>Save</button></BaseModal>
}

function InviteMembersModal({ rows, sent, error, onRowChange, onAddRow, onSend, onClose }: { rows: InviteRow[]; sent: boolean; error: boolean; onRowChange: (index: number, key: keyof InviteRow, value: string) => void; onAddRow: () => void; onSend: () => void; onClose: () => void }) {
  return <BaseModal title="Invite your team members" onClose={onClose}><p className="mt-3 text-center text-[10px] text-navy/70">Get your project up and running faster by directly inviting your team members to your project.</p><div className="mt-5 space-y-2"><div className="grid grid-cols-[1fr_110px] gap-2 px-1 text-[9px] font-bold text-[#8586a3]"><span>Email address</span><span>Role</span></div>{rows.map((row, index) => <div key={index} className="grid grid-cols-[1fr_110px] gap-2"><input value={row.email} onChange={event => onRowChange(index, 'email', event.target.value)} placeholder="name@example.com" className="h-8 rounded border border-[#e5e6ef] px-2 text-[9px] outline-none focus:border-brand" /><div className="relative"><select value={row.role} onChange={event => onRowChange(index, 'role', event.target.value)} className="h-8 w-full appearance-none rounded border border-[#e5e6ef] bg-white px-2 pr-6 text-[9px] outline-none"><option value="">Select role</option>{roles.map(role => <option key={role}>{role}</option>)}</select><ChevronDown size={12} className="pointer-events-none absolute right-2 top-2 text-[#9899bc]" /></div></div>)}</div><button onClick={onAddRow} className="mt-2 w-full border border-[#e5e6ef] py-2 text-[9px] text-[#8586a3]">+ Add more</button>{sent && <p className="mt-4 text-center text-[10px] font-semibold text-[#12a35d]">We have invited your team members via email!</p>}{error && <p className="mt-4 text-center text-[10px] font-semibold text-[#d04e4e]">Sorry, we couldn't invite your team members. Please contact us at support@example.com.</p>}<div className="mt-5 flex flex-col items-center gap-3"><button onClick={onSend} className={`${buttonClass} bg-brand text-white`}>Send invitations</button><button onClick={onClose} className="text-[10px] text-[#8586a3]">Invite later</button></div></BaseModal>
}

function OrganizationAssignmentModal({ selectedOrganizations, onToggle, onClose }: { selectedOrganizations: number[]; onToggle: (id: number) => void; onClose: () => void }) {
  const organizationRows = Array.from({ length: 8 }, (_, index) => ({ id: index + 1, name: 'Some Organization', industry: 'Industry area name' }))
  return <BaseModal title="Assignments" onClose={onClose}><p className="mt-2 text-[10px] text-navy/70">Select organizations to assign this member to.</p><div className="mt-4 space-y-2">{organizationRows.map(organization => <label key={organization.id} className="grid grid-cols-[24px_1fr_1fr] items-center rounded-lg bg-[#fafaff] px-2 py-2 text-[9px] text-navy"><input type="checkbox" checked={selectedOrganizations.includes(organization.id)} onChange={() => onToggle(organization.id)} className="accent-brand" /><span>{organization.name}</span><span>{organization.industry}</span></label>)}</div><button onClick={onClose} className={`${buttonClass} mt-auto bg-brand text-white`}>Assign to Organization</button></BaseModal>
}

function BaseModal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-4"><div className="relative flex min-h-[160px] w-full max-w-[360px] flex-col rounded-xl bg-white p-4 sm:p-5 shadow-[0_18px_45px_rgba(15,41,64,0.2)]"><button onClick={onClose} aria-label="Close" className="absolute right-5 top-5 text-[#9899bc] hover:text-navy"><X size={16} /></button><h2 className="flex items-center gap-2 text-xl font-bold text-black"><UserPlus size={16} className="text-brand" />{title}</h2>{children}</div></div> }
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="mt-3 block text-[10px] font-bold text-navy">{label}<input type={type} value={value} onChange={event => onChange(event.target.value)} placeholder="Input" className="mt-1 block h-8 w-full rounded border border-[#e5e6ef] px-2 text-[10px] outline-none focus:border-brand" /></label> }
