import { Archive, MoreHorizontal, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { buttonClass } from './constants'
import type { ImportedMember } from './types'

type Props = { users: ImportedMember[]; archived: boolean; onImport: () => void; onAdd: () => void; onGroups: () => void; onArchiveList: () => void; onActiveList: () => void; onArchive: (id: number) => void; onRestore: (id: number) => void; onEdit: (user: ImportedMember) => void }

export default function UserManagementPage({ users, archived, onImport, onAdd, onGroups, onArchiveList, onActiveList, onArchive, onRestore, onEdit }: Props) {
  const [query, setQuery] = useState('')
  const shownUsers = useMemo(() => users.filter(user => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase())), [users, query])
  return <section className="max-w-[980px] pt-1"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-[24px] font-bold tracking-[-0.03em] text-black">{archived ? 'Archived Users' : 'Users'}</h2><p className="mt-2 text-xs leading-5 text-navy/75">This section allows you to manage<br />your Organization’s Members</p></div><div className="flex flex-wrap gap-2">{archived ? <button onClick={onActiveList} className={`${buttonClass} bg-brand text-white`}>Active Users</button> : <><button onClick={onImport} className={`${buttonClass} bg-brand text-white`}>Import Users</button><button onClick={onAdd} className={`${buttonClass} bg-brand text-white`}>Add A User</button><button onClick={onArchiveList} className={`${buttonClass} bg-brand text-white`}>Archived Users</button></>}</div></div><div className="mt-5 flex items-center justify-between"><div className="flex h-8 w-[165px] items-center rounded-full bg-[#eff1ff] px-3 text-[#8b8daf]"><Search size={12} className="mr-2" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search users" className="w-full bg-transparent text-[10px] outline-none placeholder:text-[#8b8daf]" /></div>{!archived && <button onClick={onGroups} className={`${buttonClass} h-8 border border-brand bg-white px-8 text-brand`}>Groups</button>}</div><div className="mt-3 overflow-x-auto"><div className="min-w-[730px]"><div className="grid grid-cols-[2fr_1fr_1.2fr_.8fr_.5fr] px-4 pb-2 text-[10px] font-semibold text-[#8586a3]"><span>Name</span><span>Groups</span><span>Department</span><span>Role</span><span>Actions</span></div><div className="space-y-2">{shownUsers.length ? shownUsers.map(user => <div key={user.id} className="grid grid-cols-[2fr_1fr_1.2fr_.8fr_.5fr] items-center rounded-xl bg-white px-4 py-3 text-[10px] text-navy/75 shadow-[0_4px_14px_rgba(15,41,64,0.05)]"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#f1d1bd] text-[10px] font-bold">{user.name.split(' ').map(name => name[0]).join('')}</span><span><b className="block text-navy">{user.name}</b><small>{user.email}</small></span></div><span>-</span><span>{user.department}</span><span>{user.role}</span><div className="flex items-center gap-1"><button title={archived ? 'Restore user' : 'Edit user'} onClick={() => archived ? onRestore(user.id) : onEdit(user)} className="text-brand"><MoreHorizontal size={17} /></button><button title={archived ? 'Restore user' : 'Archive user'} onClick={() => archived ? onRestore(user.id) : onArchive(user.id)} className={archived ? 'text-[#12a35d]' : 'text-[#e93535]'}><Archive size={13} /></button></div></div>) : <p className="rounded-xl bg-white p-6 text-center text-xs text-navy/55">No users found.</p>}</div></div></div></section>
}
